config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers, 
    controllers:  { sessions: 'teachers/sessions', registrations: 'teachers/registrations', confirmations: 'teachers/confirmations', passwords: 'teachers/passwords' },
    path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }

  root 'dashboard#root'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'

  # SECTION SUBMODELS
  get '/sections', to: 'sections#index', as: 'sections'
  get '/sections/:id', to: 'sections#show', as: 'section'
  get '/sections/:id/seatworks', to: 'sections#view_seatworks', as: 'view_section_seatworks'
  get '/sections/:id/homeworks', to: 'sections#view_homeworks', as: 'view_section_homeworks'
  get '/sections/:id/projects', to: 'sections#view_projects', as: 'view_section_projects'
  get '/sections/:id/exams', to: 'sections#view_exams', as: 'view_section_exams'
  get '/sections/:id/attendances', to: 'sections#view_attendances', as: 'view_section_attendances'

  # SECTION PROCESSES
  post '/sections/:id/report', to: 'section_processes#section_report_to_email', as: 'section_report'
  get '/sections/:id/report', to: 'section_processes#download_report', as: 'section_report_dowload'
  put '/sections/:id/update', to: 'section_processes#update_section', as: 'section_update'
  put '/sections/:id/attendances/:attendance_id/update', to: 'section_processes#update_section_attendance', as: 'section_attendance_update'
  put '/sections/:id/seatworks/:seatwork_id/update', to: 'section_processes#update_section_seatwork', as: 'section_seatwork_update'
  put '/sections/:id/homeworks/:homework_id/update', to: 'section_processes#update_section_homework', as: 'section_homework_update'
  put '/sections/:id/projects/:project_id/update', to: 'section_processes#update_section_project', as: 'section_project_update'
  put '/sections/:id/exams/:exam_id/update', to: 'section_processes#update_section_exam', as: 'section_exam_update'
  delete '/sections/:id/delete', to: 'section_processes#destroy_section', as: 'section_delete'
  delete '/sections/:id/seatworks/:seatwork_id/delete', to: 'section_processes#destroy_section_seatwork', as: 'section_seatwork_delete'
  delete '/sections/:id/homeworks/:homework_id/delete', to: 'section_processes#destroy_section_homework', as: 'section_homework_delete'
  delete '/sections/:id/projects/:project_id/delete', to: 'section_processes#destroy_section_project', as: 'section_project_delete'
  delete '/sections/:id/exams/:exam_id/delete', to: 'section_processes#destroy_section_exam', as: 'section_exam_delete'
  delete '/sections/:id/attendances/:attendance_id/delete', to: 'section_processes#destroy_section_attendance', as: 'section_attendance_delete'

  # STUDENT SUBMODELS
  get '/sections/:id/students', to: 'students#index', as: 'students'
  get '/sections/:id/students/:student_id', to: 'students#show', as: 'student'
  get '/sections/:id/students/:student_id/homeworks', to: 'students#view_homeworks', as: 'view_student_homeworks'
  get '/sections/:id/students/:student_id/seatworks', to: 'students#view_seatworks', as: 'view_student_seatworks'
  get '/sections/:id/students/:student_id/projects', to: 'students#view_projects', as: 'view_student_projects'
  get '/sections/:id/students/:student_id/exams', to: 'students#view_exams', as: 'view_student_exams'
  get '/sections/:id/students/:student_id/absences', to: 'students#view_absences', as: 'view_student_absences'

  # STUDENT PROCESSES
  post '/sections/:id/students/:student_id/report', to: 'student_processes#student_report_to_email', as: 'student_report'
  get '/sections/:id/students/:student_id/report', to: 'student_processes#download_report', as: 'student_report_dowload'
  put '/sections/:id/students/:student_id/update', to: 'student_processes#update_student', as: 'student_update'
  put '/sections/:id/students/:student_id/seatworks/:seatwork_id', to: 'student_processes#update_student_seatwork', as: 'student_update_seatwork'
  put '/sections/:id/students/:student_id/homeworks/:homework_id', to: 'student_processes#update_student_homework', as: 'student_update_homework'
  put '/sections/:id/students/:student_id/projects/:project_id', to: 'student_processes#update_student_project', as: 'student_update_project'
  put '/sections/:id/students/:student_id/exams/:exam_id', to: 'student_processes#update_student_exam', as: 'student_update_exam'
  delete '/sections/:id/students/:student_id/delete', to: 'student_processes#destroy_student', as: 'student_delete'
  delete '/sections/:id/students/:student_id/seatworks/:seatwork_id/delete', to: 'student_processes#destroy_student_seatwork', as: 'student_delete_seatwork'
  delete '/sections/:id/students/:student_id/homeworks/:homework_id/delete', to: 'student_processes#destroy_student_homework', as: 'student_delete_homework'
  delete '/sections/:id/students/:student_id/projects/:project_id/delete', to: 'student_processes#destroy_student_project', as: 'student_delete_project'
  delete '/sections/:id/students/:student_id/exams/:exam_id/delete', to: 'student_processes#destroy_student_exam', as: 'student_delete_exam'
  delete '/sections/:id/students/:student_id/absences/:absent_id/delete', to: 'student_processes#destroy_student_attendance', as: 'student_delete_attendance'
  
  # FORMS
  get '/new/section', to: 'form#new_section', as: 'new_section_form'
  get '/new/grading-system', to: 'form#new_grading_system', as: 'new_grading_system_form'
  get '/new/seatwork/:section_id', to: 'form#new_seatwork', as: 'new_seatwork_form'
  get '/new/homework/:section_id', to: 'form#new_homework', as: 'new_homework_form'
  get '/new/project/:section_id', to: 'form#new_project', as: 'new_project_form'
  get '/new/exam/:section_id', to: 'form#new_exam', as: 'new_exam_form'
  get '/new/attendance/:section_id', to: 'form#new_attendance', as: 'new_attendance_form'

  # PROCESS FORMS
  post '/new/section', to: 'creation_processes#create_section', as: 'create_section'
  post '/new/grading-system', to: 'creation_processes#create_grading_system', as: 'create_grading_system'
  post '/new/seatwork/:section_id', to: 'creation_processes#create_seatwork', as: 'create_seatwork'
  post '/new/homework/:section_id', to: 'creation_processes#create_homework', as: 'create_homework'
  post '/new/project/:section_id', to: 'creation_processes#create_project', as: 'create_project'
  post '/new/exam/:section_id', to: 'creation_processes#create_exam', as: 'create_exam'
  post '/new/attendance/:section_id/', to: 'creation_processes#create_attendance', as: 'create_attendance'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_teacher!, except: [:root]

  def root
    render layout: 'landing'
  end

  def dashboard
    @youtube_videos = Youtube.search(current_teacher.subject)

    @students = []
    section.each { |section| @students << section.students.group(:section_id).count.values }
    @student_count = @students.map(&:sum)

    @seatworks = []
    @homeworks = []
    @projects = []
    @exams = []
    section_quarters.each do |category|
      @seatworks << Quarter::Seatwork.where(quarter_id: category[:id]).count
      @homeworks << Quarter::Homework.where(quarter_id: category[:id]).count
      @projects << Quarter::Project.where(quarter_id: category[:id]).count
      @exams << Quarter::Exam.where(quarter_id: category[:id]).count
    end
  end

  private

  def section
    @sections = current_teacher.sections
  end

  def section_quarters
    @quarters = []
    section.each { |section| @quarters << section.quarters }
    @section_quarters = @quarters.flatten
  end
end

app/views/dashboard/dashboard.html.erb
<!-- <h1>Hi Maam/Sir, you will see here the summary of your account and some educational videos related to your teaching subject that you can use or reference in your class</h1> -->
<div class="d-flex flex-wrap align-items-center justify-content-between">
  <div><h1 class="mb-0 font-weight-bold text-primary">DASHBOARD</h1></div>
  <div class="d-flex row">
    <div>
      <div class="d-flex align-items-center" style="position: relative;">
        <span class="small">SUBJECT</span>
        <div class="col-auto"><i class="fas fa-book" style="color: brown"></i></div>
        <div style="width: 100px"></div>
      </div>
      <h4 class="text-dark"><%= current_teacher.subject.upcase %></h4>
    </div>
    <div>
      <div class="d-flex align-items-center" style="position: relative;">
        <span class="small">SECTION(S)</span>
        <div class="col-auto"><i class="fas fa-chalkboard-teacher" style="color: green"></i></div>
        <div style="width: 100px"></div>
      </div>
      <h4 class="text-dark"><%= current_teacher.sections.count %></h4>
    </div>
    <div>
      <div class="d-flex align-items-center" style="position: relative;">
        <span class="small">STUDENT(S)</span>
        <div class="col-auto"><i class="fas fa-users" style="color: purple"></i></div>
        <div style="width: 20px"></div>
      </div>
      <h4 class="text-dark"><%= @student_count.sum %></h4>
    </div>
  </div>
</div><br>

<div class="row">
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            NUMBER OF SEATWORK GIVEN</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @seatworks.sum %></div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-book-reader fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            NUMBER OF HOMEWORK GIVEN</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @homeworks.sum %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-home fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            NUMBER OF PROJECTS GIVEN</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @projects.sum %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-project-diagram fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            NUMBER OF EXAMS GIVEN</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @exams.sum %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-file-signature fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<h5 class="mb-3 text-dark font-weight-bold">RECOMMENDED VIDEOS</h5>
<div class="overflow-auto">
  <ul class="list-unstyled video-list-thumbs d-flex">
    <% @youtube_videos.each do |video| %>
      <li class="col-lg-3 col-sm-4 col-xs-6">
        <a href="<%= video[:watch_url] %>" title="<%= video[:title] %>" target="_blank">
          <%= image_tag asset_path(video[:thumbnail]), class: "img-responsive", style: 'height: 100%; width: 100%' %>
          <h2 class="font-weight-bold mb-2"><%= truncate(video[:title], length: 60).gsub('&amp;#39;', '\'').gsub('&amp;quot;', '"').upcase %></h2>
          <p class="h6 small"><%= truncate(video[:description], length: 35) %></p>
          <span class="glyphicon glyphicon-play-circle"></span>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/dashboard/root.html.erb
<header id="header" class="header fixed-top">
  <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
    <a href="<%= root_path %>" class="logo d-flex align-items-center">
      <%= image_tag asset_path('logo_name.png'), 'style':"height: 200%" %>
    </a>
    <nav id="navbar" class="navbar">
      <ul>
        <% if current_teacher %>
          <li></li>
          <li><%= link_to 'LOGOUT', destroy_teacher_session_path, class: 'getstarted scrollto', method: 'delete' %></li>
        <% else %>
          <li><a class="nav-link scrollto active" href="<%= root_path %>">HOME</a></li>
          <li><%= link_to 'SIGN IN', teacher_session_path, class: 'getstarted scrollto' %></li>
        <% end %>
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav>
  </div>
</header>

<section id="hero" class="hero d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center">
        <h1 data-aos="fade-up" style="color: #464646">Modern workspace designed for <span style="color: #4E73DF">teachers</span></h1>
        <h4 data-aos="fade-up" data-aos-delay="400" class="text-muted mt-2">
          <i class="fas fa-check mr-3 text-primary"></i>Keep track of student progress<br>
          <i class="fas fa-check mr-3 text-primary"></i>Generate academic reports easily<br>
          <i class="fas fa-check mr-3 mb-3 text-primary"></i>Find video content for lessons<br>
          <span class="text-primary font-weight-bold">All within one platform.</span>
        </h4>
        <div data-aos="fade-up" data-aos-delay="600">
          <% if current_teacher %>
          <p class="text-danger text-uppercase mb-0 font-weight-bold">You are logged in!</p>
          <div class="text-center text-lg-start d-flex justify-content-start">
              <a href="<%= dashboard_path %>" class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center p-4">
                <span>GO TO DASHBOARD</span>
                <i class="bi bi-arrow-right"></i>
              </a>
          </div>
          <% else %>
            <div class="text-center text-lg-start d-flex justify-content-start">
              <a href="<%= new_teacher_registration_path %>" class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center p-4">
                <span>CREATE AN ACCOUNT</span>
                <i class="bi bi-arrow-right"></i>
              </a>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
        <%= image_tag asset_path('teaching-animate.svg') %>
      </div>
    </div>
  </div>
</section>