config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers, 
    controllers:  { sessions: 'teachers/sessions', registrations: 'teachers/registrations', confirmations: 'teachers/confirmations', passwords: 'teachers/passwords' },
    path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }

  root 'dashboard#root'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'

  # SECTION SUBMODELS
  get '/sections', to: 'sections#index', as: 'sections'
  get '/sections/:id', to: 'sections#show', as: 'section'
  get '/sections/:id/seatworks', to: 'sections#view_seatworks', as: 'view_section_seatworks'
  get '/sections/:id/homeworks', to: 'sections#view_homeworks', as: 'view_section_homeworks'
  get '/sections/:id/projects', to: 'sections#view_projects', as: 'view_section_projects'
  get '/sections/:id/exams', to: 'sections#view_exams', as: 'view_section_exams'
  get '/sections/:id/attendances', to: 'sections#view_attendances', as: 'view_section_attendances'

  # SECTION PROCESSES
  post '/sections/:id/report', to: 'section_processes#section_report_to_email', as: 'section_report'
  get '/sections/:id/report', to: 'section_processes#download_report', as: 'section_report_dowload'
  put '/sections/:id/update', to: 'section_processes#update_section', as: 'section_update'
  put '/sections/:id/attendances/:attendance_id/update', to: 'section_processes#update_section_attendance', as: 'section_attendance_update'
  put '/sections/:id/seatworks/:seatwork_id/update', to: 'section_processes#update_section_seatwork', as: 'section_seatwork_update'
  put '/sections/:id/homeworks/:homework_id/update', to: 'section_processes#update_section_homework', as: 'section_homework_update'
  put '/sections/:id/projects/:project_id/update', to: 'section_processes#update_section_project', as: 'section_project_update'
  put '/sections/:id/exams/:exam_id/update', to: 'section_processes#update_section_exam', as: 'section_exam_update'
  delete '/sections/:id/delete', to: 'section_processes#destroy_section', as: 'section_delete'
  delete '/sections/:id/seatworks/:seatwork_id/delete', to: 'section_processes#destroy_section_seatwork', as: 'section_seatwork_delete'
  delete '/sections/:id/homeworks/:homework_id/delete', to: 'section_processes#destroy_section_homework', as: 'section_homework_delete'
  delete '/sections/:id/projects/:project_id/delete', to: 'section_processes#destroy_section_project', as: 'section_project_delete'
  delete '/sections/:id/exams/:exam_id/delete', to: 'section_processes#destroy_section_exam', as: 'section_exam_delete'
  delete '/sections/:id/attendances/:attendance_id/delete', to: 'section_processes#destroy_section_attendance', as: 'section_attendance_delete'

  # STUDENT SUBMODELS
  get '/sections/:id/students', to: 'students#index', as: 'students'
  get '/sections/:id/students/:student_id', to: 'students#show', as: 'student'
  get '/sections/:id/students/:student_id/homeworks', to: 'students#view_homeworks', as: 'view_student_homeworks'
  get '/sections/:id/students/:student_id/seatworks', to: 'students#view_seatworks', as: 'view_student_seatworks'
  get '/sections/:id/students/:student_id/projects', to: 'students#view_projects', as: 'view_student_projects'
  get '/sections/:id/students/:student_id/exams', to: 'students#view_exams', as: 'view_student_exams'
  get '/sections/:id/students/:student_id/absences', to: 'students#view_absences', as: 'view_student_absences'

  # STUDENT PROCESSES
  post '/sections/:id/students/:student_id/report', to: 'student_processes#student_report_to_email', as: 'student_report'
  get '/sections/:id/students/:student_id/report', to: 'student_processes#download_report', as: 'student_report_dowload'
  put '/sections/:id/students/:student_id/update', to: 'student_processes#update_student', as: 'student_update'
  put '/sections/:id/students/:student_id/seatworks/:seatwork_id', to: 'student_processes#update_student_seatwork', as: 'student_update_seatwork'
  put '/sections/:id/students/:student_id/homeworks/:homework_id', to: 'student_processes#update_student_homework', as: 'student_update_homework'
  put '/sections/:id/students/:student_id/projects/:project_id', to: 'student_processes#update_student_project', as: 'student_update_project'
  put '/sections/:id/students/:student_id/exams/:exam_id', to: 'student_processes#update_student_exam', as: 'student_update_exam'
  delete '/sections/:id/students/:student_id/delete', to: 'student_processes#destroy_student', as: 'student_delete'
  delete '/sections/:id/students/:student_id/seatworks/:seatwork_id/delete', to: 'student_processes#destroy_student_seatwork', as: 'student_delete_seatwork'
  delete '/sections/:id/students/:student_id/homeworks/:homework_id/delete', to: 'student_processes#destroy_student_homework', as: 'student_delete_homework'
  delete '/sections/:id/students/:student_id/projects/:project_id/delete', to: 'student_processes#destroy_student_project', as: 'student_delete_project'
  delete '/sections/:id/students/:student_id/exams/:exam_id/delete', to: 'student_processes#destroy_student_exam', as: 'student_delete_exam'
  delete '/sections/:id/students/:student_id/absences/:absent_id/delete', to: 'student_processes#destroy_student_attendance', as: 'student_delete_attendance'
  
  # FORMS
  get '/new/section', to: 'form#new_section', as: 'new_section_form'
  get '/new/grading-system', to: 'form#new_grading_system', as: 'new_grading_system_form'
  get '/new/seatwork/:section_id', to: 'form#new_seatwork', as: 'new_seatwork_form'
  get '/new/homework/:section_id', to: 'form#new_homework', as: 'new_homework_form'
  get '/new/project/:section_id', to: 'form#new_project', as: 'new_project_form'
  get '/new/exam/:section_id', to: 'form#new_exam', as: 'new_exam_form'
  get '/new/attendance/:section_id', to: 'form#new_attendance', as: 'new_attendance_form'

  # PROCESS FORMS
  post '/new/section', to: 'creation_processes#create_section', as: 'create_section'
  post '/new/grading-system', to: 'creation_processes#create_grading_system', as: 'create_grading_system'
  post '/new/seatwork/:section_id', to: 'creation_processes#create_seatwork', as: 'create_seatwork'
  post '/new/homework/:section_id', to: 'creation_processes#create_homework', as: 'create_homework'
  post '/new/project/:section_id', to: 'creation_processes#create_project', as: 'create_project'
  post '/new/exam/:section_id', to: 'creation_processes#create_exam', as: 'create_exam'
  post '/new/attendance/:section_id/', to: 'creation_processes#create_attendance', as: 'create_attendance'
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  belongs_to :section
  has_many :homeworks, dependent: :destroy
  has_many :seatworks, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :exams, dependent: :destroy
  has_many :absents, dependent: :destroy
end

app/models/student/absent.rb
class Student::Absent < ApplicationRecord
  belongs_to :student
  belongs_to :quarter, inverse_of: :student_absents
  belongs_to :quarter_attendance, class_name: 'Quarter::Attendance', inverse_of: :student_absents
end

app/models/student/exam.rb
class Student::Exam < ApplicationRecord
  validates :score, presence: true
  belongs_to :student
  belongs_to :quarter, inverse_of: :student_exams
  belongs_to :quarter_exam, class_name: 'Quarter::Exam', inverse_of: :student_exams
end

app/models/student/homework.rb
class Student::Homework < ApplicationRecord
  validates :score, presence: true
  belongs_to :student
  belongs_to :quarter, inverse_of: :student_homeworks
  belongs_to :quarter_homework, class_name: 'Quarter::Homework', inverse_of: :student_homeworks
end

app/models/student/project.rb
class Student::Project < ApplicationRecord
  validates :score, presence: true
  belongs_to :student
  belongs_to :quarter, inverse_of: :student_projects
  belongs_to :quarter_project, class_name: 'Quarter::Project', inverse_of: :student_projects
end

app/models/student/seatwork.rb
class Student::Seatwork < ApplicationRecord
  validates :score, presence: true
  belongs_to :student
  belongs_to :quarter, inverse_of: :student_seatworks
  belongs_to :quarter_seatwork, class_name: 'Quarter::Seatwork', inverse_of: :student_seatworks
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_student, except: [:index]
  before_action :set_active_quarter, except: [:index]

  def index
    @section = Section.find(params[:id])
    @students = Section.find(params[:id]).students
  end

  def show; end

  def view_seatworks
    @student_seatworks = @student.seatworks.where(quarter_id: @active_quarter.id)
  end

  def view_homeworks
    @student_homeworks = @student.homeworks.where(quarter_id: @active_quarter.id)
  end

  def view_projects
    @student_projects = @student.projects.where(quarter_id: @active_quarter.id)
  end

  def view_exams
    @student_exams = @student.exams.where(quarter_id: @active_quarter.id)
  end

  def view_absences
    @student_absents = @student.absents.where(quarter_id: @active_quarter.id)
  end

  private

  def set_student
    @student = Student.find_by(id: params[:student_id], section_id: params[:id])
  end

  def set_active_quarter
    @section = @student.section
    @active_quarter = @section.quarters.find_by(sequence: @section.active_quarter)
  end
end

app/views/students/index.html.erb
<!-- <h1>Hi Maam/Sir, this is where you view the list of students in a section</h1>
<h1>name of students are rendered automatically</h1> -->

<div class="card shadow mb-4">
  <div class="card-header py-3 table-responsive d-flex justify-content-around">
    <h5 class="m-0 text-muted mb-2">QUARTER : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.active_quarter %></h5>
    <h5 class="m-0 text-muted mb-2">SECTION : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.name.upcase %></h5>
    <h5 class="m-0 text-muted mb-2">NO. OF STUDENTS : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.students.count %></span></h5>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="200" cellspacing="0">
        <thead>
          <tr class="text-dark">
            <th scope="col">LAST NAME</th>
            <th scope="col">FIRST NAME</th>
            <th scope="col">EMAIL</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <tr>
              <td><%= student.last_name.capitalize %></td>
              <td><%= student.first_name.capitalize %></td>
              <td><%= student.email %></td>
              <td>
                <div class="d-flex justify-content-around">
                  <a class="btn btn-primary btn-circle text-center" href="<%= student_path(student.section_id, student.id) %>">
                      <i class="fas fa-eye"></i>
                  </a>
                  <a class="btn btn-warning btn-circle text-center" href="#" data-toggle="modal" data-target="#updateStudentModal_<%= student.id %>">
                      <i class="fas fa-pencil-alt"></i>
                  </a>
                  <a class="btn btn-danger btn-circle text-center" href="#" data-toggle="modal" data-target="#deleteStudentModal_<%= student.id %>">
                      <i class="fas fa-trash"></i>
                  </a>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>    
      </table>
    </div>
  </div>
</div>

<%# UPDATE STUDENT MODAL %>
<% @students.each do |student| %>
  <div class="modal fade" id="updateStudentModal_<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="student_update_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Student Details</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <p class="mb-2 font-weight-bold h3 text-dark"><%= student.last_name.upcase %>, <%= student.first_name.upcase %></p>
          <p class="mb-4 font-weight-bold h3 text-dark"><%= student.email %></p>
          <%= form_with method: :put, scope: :student, url: student_update_path(id: student.section_id, student_id: student.id), local: true do |f| %>
            <div class = "form-group">
              <%= f.text_field :first_name, 'placeholder': "First Name", required: true, class: "form-control m-auto", 'style': "width: 50%" %><br>
              <%= f.text_field :last_name, 'placeholder': "Last Name", required: true, class: "form-control m-auto", 'style': "width: 50%" %><br>
              <%= f.email_field :email, 'placeholder': "Email", required: true, class: "form-control m-auto", 'style': "width: 50%" %><br>
            </div>
            <%= f.submit "UPDATE", class:'btn btn-warning', 'style': "width: 50%" %></br>
          <% end %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

<%# DELETE EXAM MODAL %>
<% @students.each do |student| %>
  <div class="modal fade" id="deleteStudentModal_<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="student_delete_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Student</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <p class="mb-2 font-weight-bold h3 text-dark"><%= student.last_name.upcase %>, <%= student.first_name.upcase %></p>
          <p class="text-danger h6">Are you sure you want to delete this record?<br>This process cannot be undone.</p><br>
          <%= link_to 'DELETE', student_delete_path(id: student.section_id, student_id: student.id), class: 'btn btn-danger px-5', method: :delete %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/show.html.erb
<!-- <h1>Hi Maam/Sir, this is where you view a specific student of a section</h1>
<h1>student information is rendered automatically</h1> -->

<div class="card shadow mb-4 mesa">
  <div class="card-header py-3">
    <table class="table table-bordered">
      <thead>
       <tr>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">QUARTER</td>
         <td class="text-dark h5 font-weight-bold"><%= @section.active_quarter %></td>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">STUDENT NAME</td>
         <td class="text-dark h5 font-weight-bold"><%= @student.last_name %>, <%= @student.first_name %></td>
       </tr>
      </thead>
      <tbody>
      <tr>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">SECTION</td>
         <td class="text-dark h5 font-weight-bold"><%= @section.name %></td>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">STUDENT EMAIL</td>
         <td class="text-dark h5 font-weight-bold"><%= @student.email %></td>
       </tr>
      </tbody>
    </table>
  </div>
  <div class="card-body">
    <div class="d-sm-flex align-items-center justify-content-end mb-4">
      <%= link_to student_report_path(id: @section.id, student_id: @student.id), method: 'post', class: 'btn btn-primary btn-icon-split ml-2' do %>
        <span class="icon text-white-50">
          <i class="fas fa-paper-plane"></i>
        </span>
        <span class="text">Send Report to Student</span>
      <% end %>

      <%= link_to student_report_dowload_path(id: @section.id, student_id: @student.id), class: 'btn btn-primary btn-icon-split ml-2' do %>
        <span class="icon text-white-50">
          <i class="fas fa-download"></i>
        </span>
        <span class="text">Download Report</span>
      <% end %>
    </div>
    <div class="row d-flex justify-content-around">
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_student_seatworks_path(@student.section_id, @student.id) %>">
          <div class="card border border-primary rounded shadow h-100 py-2">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-book-reader fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-4">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2" style="color: #AB4967">SEATWORK</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_student_homeworks_path(@student.section_id, @student.id) %>">
          <div class="card border border-primary rounded shadow h-100 py-2">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-home fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-3">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2" style="color: #5B8266">HOMEWORK</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <div class="row d-flex justify-content-around">
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_student_projects_path(@student.section_id, @student.id) %>">
          <div class="card border border-primary rounded shadow h-100 py-2">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-project-diagram fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-4">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2" style="color: #785589">PROJECTS</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_student_exams_path(@student.section_id, @student.id) %>">
          <div class="card border border-primary rounded shadow h-100 py-2">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-file-signature fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-3">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2" style="color: #B49A67">EXAMS</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_student_absences_path(@student.section_id, @student.id) %>">
          <div class="card border border-primary rounded shadow h-100 py-2">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-user-check fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-3">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2" style="color: #A2708A">ATTENDANCE</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', students_path(@student.section_id), class: "btn btn-info px-4 font-weight-bold", 'style': "background: #4E73DF" %>
</div><br>

app/views/students/view_exams.html.erb
<!-- <h1>Hi Maam/Sir, this is where you view the exams of a specific student of a section</h1>
<h1>student exams list is rendered automatically</h1> -->

<div class="card shadow mb-4 mesa">
  <div class="card-header py-3 table-responsive">
    <!-- <h6 class="m-0 text-muted mb-2">QUARTER : <span class="ml-5 pl-5 text-primary h5 font-weight-bold"><%= @section.active_quarter %></h6>
    <h6 class="m-0 text-muted mb-2">SECTION : <span class="ml-5 pl-5 text-primary h5 font-weight-bold"><%= @section.name.upcase %></h6><br>
    <h6 class="m-0 text-muted mb-2">STUDENT NAME : <span class="ml-4 pl-3 text-primary h5 font-weight-bold"><%= @student.last_name %>, <%= @student.first_name %></span></h6>
    <h6 class="m-0 text-muted mb-2">STUDENT EMAIL : <span class="ml-4 pl-3 text-primary h5 font-weight-bold"><%= @student.email %></span></h6> -->
    
    <table class="table table-bordered">
      <thead>
       <tr>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">QUARTER</td>
         <td class="text-dark h5 font-weight-bold"><%= @section.active_quarter %></td>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">STUDENT NAME</td>
         <td class="text-dark h5 font-weight-bold"><%= @student.last_name %>, <%= @student.first_name %></td>
       </tr>
      </thead>
      <tbody>
      <tr>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">SECTION</td>
         <td class="text-dark h5 font-weight-bold"><%= @section.name %></td>
         <td class="text-light h6 font-weight-bold" style="background: #4E73DF">STUDENT EMAIL</td>
         <td class="text-dark h5 font-weight-bold"><%= @student.email %></td>
       </tr>
      </tbody>
    </table>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="200" cellspacing="0">
        <thead>
          <tr class="text-dark">
            <th scope="col" style="color: #B49A67">EXAM</th>
            <th scope="col">Raw Score</th>
            <th scope="col">Max Score</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @student_exams.each do |exam| %>
            <tr>
              <td><%= exam.quarter_exam.title %></td>
              <td class="font-weight-bold" style="color: #B49A67"><%= exam.score %></td>
              <td><%= exam.quarter_exam.max_score %></td>
              <td>
                <div class="d-flex justify-content-around">
                  <a class="btn btn-warning btn-circle text-center" href="#" data-toggle="modal" data-target="#updateExamModal_<%= exam.id %>">
                      <i class="fas fa-pencil-alt"></i>
                  </a>
                  <a class="btn btn-danger btn-circle text-center" href="#" data-toggle="modal" data-target="#deleteExamModal_<%= exam.id %>">
                      <i class="fas fa-trash"></i>
                  </a>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>    
      </table>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', student_path(@student.section_id, @student.id), class: "btn btn-info px-4 font-weight-bold", 'style': "background: #B49A67; border-color: #B49A67" %>
</div>

<%# UPDATE EXAM MODAL %>
<% @student_exams.each do |exam| %>
  <div class="modal fade" id="updateExamModal_<%= exam.id %>" tabindex="-1" role="dialog" aria-labelledby="exam_update_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Exam</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="mb-4 font-weight-bold h3 text-dark text-center"><%= exam.quarter_exam.title.upcase %></p>
          <%= form_with method: :put, scope: :student_score, url: student_update_exam_path(id: @student.section_id, student_id: @student.id, exam_id: exam.id), local: true do |f| %>
            <div class = "form-group d-flex justify-content-center align-items-center">
              <%= f.label :score, class: 'h4 my-2 mx-2 mr-3 font-weight-bold' %>
              <%= f.number_field :score, 'style': "width: 15%", class: "form-control" %>
              <%= f.submit "UPDATE", class:'btn btn-warning my-2 mx-2 ml-3' %></br>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

<%# DELETE EXAM MODAL %>
<% @student_exams.each do |exam| %>
  <div class="modal fade" id="deleteExamModal_<%= exam.id %>" tabindex="-1" role="dialog" aria-labelledby="exam_delete_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Exam</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <p class="mb-2 font-weight-bold h3 text-dark"><%= exam.quarter_exam.title.upcase %></p>
          <p class="text-danger h6">Are you sure you want to delete this record?<br>This process cannot be undone.</p><br>
          <%= link_to 'DELETE', student_delete_exam_path(id: @student.section_id, student_id: @student.id, exam_id: exam.id), class: 'btn btn-danger px-5', method: :delete %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>