config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers, 
    controllers:  { sessions: 'teachers/sessions', registrations: 'teachers/registrations', confirmations: 'teachers/confirmations', passwords: 'teachers/passwords' },
    path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }

  root 'dashboard#root'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'

  # SECTION SUBMODELS
  get '/sections', to: 'sections#index', as: 'sections'
  get '/sections/:id', to: 'sections#show', as: 'section'
  get '/sections/:id/seatworks', to: 'sections#view_seatworks', as: 'view_section_seatworks'
  get '/sections/:id/homeworks', to: 'sections#view_homeworks', as: 'view_section_homeworks'
  get '/sections/:id/projects', to: 'sections#view_projects', as: 'view_section_projects'
  get '/sections/:id/exams', to: 'sections#view_exams', as: 'view_section_exams'
  get '/sections/:id/attendances', to: 'sections#view_attendances', as: 'view_section_attendances'

  # SECTION PROCESSES
  post '/sections/:id/report', to: 'section_processes#section_report_to_email', as: 'section_report'
  get '/sections/:id/report', to: 'section_processes#download_report', as: 'section_report_dowload'
  put '/sections/:id/update', to: 'section_processes#update_section', as: 'section_update'
  put '/sections/:id/attendances/:attendance_id/update', to: 'section_processes#update_section_attendance', as: 'section_attendance_update'
  put '/sections/:id/seatworks/:seatwork_id/update', to: 'section_processes#update_section_seatwork', as: 'section_seatwork_update'
  put '/sections/:id/homeworks/:homework_id/update', to: 'section_processes#update_section_homework', as: 'section_homework_update'
  put '/sections/:id/projects/:project_id/update', to: 'section_processes#update_section_project', as: 'section_project_update'
  put '/sections/:id/exams/:exam_id/update', to: 'section_processes#update_section_exam', as: 'section_exam_update'
  delete '/sections/:id/delete', to: 'section_processes#destroy_section', as: 'section_delete'
  delete '/sections/:id/seatworks/:seatwork_id/delete', to: 'section_processes#destroy_section_seatwork', as: 'section_seatwork_delete'
  delete '/sections/:id/homeworks/:homework_id/delete', to: 'section_processes#destroy_section_homework', as: 'section_homework_delete'
  delete '/sections/:id/projects/:project_id/delete', to: 'section_processes#destroy_section_project', as: 'section_project_delete'
  delete '/sections/:id/exams/:exam_id/delete', to: 'section_processes#destroy_section_exam', as: 'section_exam_delete'
  delete '/sections/:id/attendances/:attendance_id/delete', to: 'section_processes#destroy_section_attendance', as: 'section_attendance_delete'

  # STUDENT SUBMODELS
  get '/sections/:id/students', to: 'students#index', as: 'students'
  get '/sections/:id/students/:student_id', to: 'students#show', as: 'student'
  get '/sections/:id/students/:student_id/homeworks', to: 'students#view_homeworks', as: 'view_student_homeworks'
  get '/sections/:id/students/:student_id/seatworks', to: 'students#view_seatworks', as: 'view_student_seatworks'
  get '/sections/:id/students/:student_id/projects', to: 'students#view_projects', as: 'view_student_projects'
  get '/sections/:id/students/:student_id/exams', to: 'students#view_exams', as: 'view_student_exams'
  get '/sections/:id/students/:student_id/absences', to: 'students#view_absences', as: 'view_student_absences'

  # STUDENT PROCESSES
  post '/sections/:id/students/:student_id/report', to: 'student_processes#student_report_to_email', as: 'student_report'
  get '/sections/:id/students/:student_id/report', to: 'student_processes#download_report', as: 'student_report_dowload'
  put '/sections/:id/students/:student_id/update', to: 'student_processes#update_student', as: 'student_update'
  put '/sections/:id/students/:student_id/seatworks/:seatwork_id', to: 'student_processes#update_student_seatwork', as: 'student_update_seatwork'
  put '/sections/:id/students/:student_id/homeworks/:homework_id', to: 'student_processes#update_student_homework', as: 'student_update_homework'
  put '/sections/:id/students/:student_id/projects/:project_id', to: 'student_processes#update_student_project', as: 'student_update_project'
  put '/sections/:id/students/:student_id/exams/:exam_id', to: 'student_processes#update_student_exam', as: 'student_update_exam'
  delete '/sections/:id/students/:student_id/delete', to: 'student_processes#destroy_student', as: 'student_delete'
  delete '/sections/:id/students/:student_id/seatworks/:seatwork_id/delete', to: 'student_processes#destroy_student_seatwork', as: 'student_delete_seatwork'
  delete '/sections/:id/students/:student_id/homeworks/:homework_id/delete', to: 'student_processes#destroy_student_homework', as: 'student_delete_homework'
  delete '/sections/:id/students/:student_id/projects/:project_id/delete', to: 'student_processes#destroy_student_project', as: 'student_delete_project'
  delete '/sections/:id/students/:student_id/exams/:exam_id/delete', to: 'student_processes#destroy_student_exam', as: 'student_delete_exam'
  delete '/sections/:id/students/:student_id/absences/:absent_id/delete', to: 'student_processes#destroy_student_attendance', as: 'student_delete_attendance'
  
  # FORMS
  get '/new/section', to: 'form#new_section', as: 'new_section_form'
  get '/new/grading-system', to: 'form#new_grading_system', as: 'new_grading_system_form'
  get '/new/seatwork/:section_id', to: 'form#new_seatwork', as: 'new_seatwork_form'
  get '/new/homework/:section_id', to: 'form#new_homework', as: 'new_homework_form'
  get '/new/project/:section_id', to: 'form#new_project', as: 'new_project_form'
  get '/new/exam/:section_id', to: 'form#new_exam', as: 'new_exam_form'
  get '/new/attendance/:section_id', to: 'form#new_attendance', as: 'new_attendance_form'

  # PROCESS FORMS
  post '/new/section', to: 'creation_processes#create_section', as: 'create_section'
  post '/new/grading-system', to: 'creation_processes#create_grading_system', as: 'create_grading_system'
  post '/new/seatwork/:section_id', to: 'creation_processes#create_seatwork', as: 'create_seatwork'
  post '/new/homework/:section_id', to: 'creation_processes#create_homework', as: 'create_homework'
  post '/new/project/:section_id', to: 'creation_processes#create_project', as: 'create_project'
  post '/new/exam/:section_id', to: 'creation_processes#create_exam', as: 'create_exam'
  post '/new/attendance/:section_id/', to: 'creation_processes#create_attendance', as: 'create_attendance'
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_section_and_students, except: %i[new_section new_grading_system]
  before_action :set_grading_systems, only: [:new_section]

  def new_grading_system; end

  def new_section; end

  def new_seatwork; end

  def new_homework; end

  def new_project; end

  def new_exam; end

  def new_attendance; end

  private

  def set_section_and_students
    @section = Section.find(params[:section_id])
    @students = @section.students.order(:last_name)
  end

  def set_grading_systems
    @grading_systems = GradingSystem.where(teacher_id: current_teacher.id)
  end
end

app/views/form/_activity_fields.html.erb
<div class="form-group row">
  <%= form.label :title, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= form.text_field :'details[title]', class: 'form-control', required: true, autocomplete: :off %>
  </div>
</div>

<div class="form-group row">
  <%= form.label :max_score, class: 'col-sm-2 col-form-label' %>
  <div class="col-sm-10">
    <%= form.number_field :'details[max_score]', class: 'form-control', required: true %>
  </div>
</div>

<table class="table table-bordered dataTable table-striped table-hover" style="width: 100%;">
  <thead>
      <tr role="row">
        <th rowspan="1" colspan="1" style="width: 173px;">
          Student Name
        </th>
        <th class="text-center" rowspan="1" colspan="1" style="width: 173px;">
          Score
        </th>
      </tr>
  </thead>

  <tbody>

    <% @students.each do |student| %>
      <tr role="row">
        <td>
          <b><%= student.last_name %></b>, <%= student.first_name %>
        </td>
        <td class='d-flex justify-content-center' style="border-color: transparent">
          <input type='number' name="section_students[<%= student.id %>[score]]" class="form-control text-center">
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

<div class="form-group">
  <%= form.button type: 'submit', class: 'btn btn-success btn-circle btn-md float-right' do %>
    <i class="fas fa-paper-plane"></i>
  <% end %>
</div>

app/views/form/new_attendance.html.erb
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">

  <div class="mb-4 text-gray-800 d-flex align-items-end justify-content-between">
    <h1 class="h3">New Attendance</h1>
    <h3 class='text-primary fw-bold h1' style="font-weight: 600"><%= @section.name %></h3>
  </div>

</div>
</div>

<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">
<div class="card shadow mb-4 p-4">

<%= form_with url: create_attendance_path do |form| %>

  <div class="form-group row">
    <%= form.label :date, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.date_field :'details[date]', class: 'form-control', required: true %>
    </div>
  </div>

  <table class="table table-bordered dataTable table-striped table-hover" style="width: 100%;">
    <thead>
        <tr role="row">
          <th rowspan="1" colspan="1" style="width: 173px;">
            Student Name
          </th>
          <th class="text-center" rowspan="1" colspan="1" style="width: 173px;">
            Present?
          </th>
        </tr>
    </thead>

    <tbody>

      <% @students.each do |student| %>
        <tr role="row">
          <td>
            <b><%= student.last_name %></b>, <%= student.first_name %>
          </td>
          <td class='d-flex justify-content-center' style="border-color: transparent">
            <input type='checkbox' name="section_students[<%= student.id %>]">
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>

  <div class="form-group">
    <%= form.button type: 'submit', class: 'btn btn-success btn-circle btn-md float-right' do %>
      <i class="fas fa-paper-plane"></i>
    <% end %>
  </div>

<% end %>

</div>
</div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', view_section_attendances_path(@section.id), class: "btn btn-primary px-4 font-weight-bold" %>
</div><br>

app/views/form/new_exam.html.erb
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">

  <div class="mb-4 text-gray-800 d-flex align-items-end justify-content-between">
    <h1 class="h3">New Exam</h1>
    <h3 class='text-primary fw-bold h1' style="font-weight: 600"><%= @section.name %></h3>
  </div>

</div>
</div>

<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">
<div class="card shadow mb-4 p-4">

<%= form_with url: create_exam_path do |form| %>

  <%= render 'form/activity_fields', form: form %>

<% end %>

</div>
</div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', view_section_exams_path(@section.id), class: "btn btn-primary px-4 font-weight-bold" %>
</div><br>

<%= javascript_pack_tag 'new_requirement', 'data-turbolinks-track': 'reload' %>

app/views/form/new_grading_system.html.erb
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">

  <h1 class="h3 mb-1 text-gray-800">New Grading System</h1>

  <p class="mb-4">A Grading System will allow you to set the percentage of each requirements that should sum up to 100. This is going to be used upon the generation of report for each students. You can create multiple Grading Systems and apply it to different sections that you are teaching.</p>

</div>
</div>

<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">
<div class="card shadow mb-4 p-4">

<%= form_with url: create_grading_system_path do |form| %>

  <div class="form-group row">
    <%= form.label :seatwork, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.number_field :'details[seatwork]', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :homework, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.number_field :'details[homework]', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :exam, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.number_field :'details[exam]', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :project, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.number_field :'details[project]', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :attendance, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.number_field :'details[attendance]', class: 'form-control' %>
    </div>
  </div>

  <hr>

  <div class="form-group">
    <%= form.button type: 'submit', class: 'btn btn-success btn-circle btn-md float-right' do %>
      <i class="fas fa-paper-plane"></i>
    <% end %>
  </div>

<% end %>
 
</div>
</div>
</div>

<%= javascript_pack_tag 'new_requirement', 'data-turbolinks-track': 'reload' %>

app/views/form/new_homework.html.erb
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">

  <div class="mb-4 text-gray-800 d-flex align-items-end justify-content-between">
    <h1 class="h3">New Homework</h1>
    <h3 class='text-primary fw-bold h1' style="font-weight: 600"><%= @section.name %></h3>
  </div>

</div>
</div>

<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">
<div class="card shadow mb-4 p-4">

<%= form_with url: create_homework_path do |form| %>

  <%= render 'form/activity_fields', form: form %>

<% end %>

</div>
</div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', view_section_homeworks_path(@section.id), class: "btn btn-primary px-4 font-weight-bold" %>
</div><br>

<%= javascript_pack_tag 'new_requirement', 'data-turbolinks-track': 'reload' %>

app/views/form/new_project.html.erb
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">

  <div class="mb-4 text-gray-800 d-flex align-items-end justify-content-between">
    <h1 class="h3">New Project</h1>
    <h3 class='text-primary fw-bold h1' style="font-weight: 600"><%= @section.name %></h3>
  </div>

</div>
</div>

<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">
<div class="card shadow mb-4 p-4">

<%= form_with url: create_project_path do |form| %>

  <%= render 'form/activity_fields', form: form %>

<% end %>

</div>
</div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', view_section_projects_path(@section.id), class: "btn btn-primary px-4 font-weight-bold" %>
</div><br>

<%= javascript_pack_tag 'new_requirement', 'data-turbolinks-track': 'reload' %>

app/views/form/new_seatwork.html.erb
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">

  <div class="mb-4 text-gray-800 d-flex align-items-end justify-content-between">
    <h1 class="h3">New Seatwork</h1>
    <h3 class='text-primary fw-bold h1' style="font-weight: 600"><%= @section.name %></h3>
  </div>

</div>
</div>

<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">
<div class="card shadow mb-4 p-4">

<%= form_with url: create_seatwork_path do |form| %>

  <%= render 'form/activity_fields', form: form %>

<% end %>

</div>
</div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', view_section_seatworks_path(@section.id), class: "btn btn-primary px-4 font-weight-bold" %>
</div><br>

<%= javascript_pack_tag 'new_requirement', 'data-turbolinks-track': 'reload' %>

app/views/form/new_section.html.erb
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">

  <h1 class="h3 mb-4 text-gray-800">
    New Section
  </h1>

</div>
</div>

<div class="row justify-content-center">
<div class="col-xl-8 col-lg-7">
<div class="card shadow mb-4 p-4">

<%= form_with url: create_section_path, id: 'create-section-form' do |form| %>

  <div class="form-group row align-items-center">
    <%= form.label :name, 'Name', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= form.text_field :'details[name]', class: 'form-control', required: true, autocomplete: :off %>
    </div>
  </div>

  <div class="form-group row align-items-center">
    <%= form.label :name, 'Grading System', class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <select name="grading_system" class="form-control">
        <% @grading_systems.each_with_index do |grading_system, index| %>
          <option value="<%= grading_system.id %>" >Grading System <%= index + 1 %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group row student-row-header">
    <div class="col-sm-12">
      <h3>
        Students
        <%= form.button type: 'button', class: 'btn btn-primary btn-md float-right', id: 'add-student-btn' do %>
        <i class="fas fa-plus-circle"></i> Add Student
        <% end %>
      </h3>
    </div>
  </div>

  <hr>

  <div class="form-group">
    <%= form.button type: 'submit', class: 'btn btn-success btn-circle btn-md float-right' do %>
      <i class="fas fa-paper-plane"></i>
    <% end %>
  </div>

<% end %>

</div>
</div>
</div>

<%= javascript_pack_tag 'new_section', 'data-turbolinks-track': 'reload' %>