config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers, 
    controllers:  { sessions: 'teachers/sessions', registrations: 'teachers/registrations', confirmations: 'teachers/confirmations', passwords: 'teachers/passwords' },
    path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }

  root 'dashboard#root'
  get '/dashboard', to: 'dashboard#dashboard', as: 'dashboard'

  # SECTION SUBMODELS
  get '/sections', to: 'sections#index', as: 'sections'
  get '/sections/:id', to: 'sections#show', as: 'section'
  get '/sections/:id/seatworks', to: 'sections#view_seatworks', as: 'view_section_seatworks'
  get '/sections/:id/homeworks', to: 'sections#view_homeworks', as: 'view_section_homeworks'
  get '/sections/:id/projects', to: 'sections#view_projects', as: 'view_section_projects'
  get '/sections/:id/exams', to: 'sections#view_exams', as: 'view_section_exams'
  get '/sections/:id/attendances', to: 'sections#view_attendances', as: 'view_section_attendances'

  # SECTION PROCESSES
  post '/sections/:id/report', to: 'section_processes#section_report_to_email', as: 'section_report'
  get '/sections/:id/report', to: 'section_processes#download_report', as: 'section_report_dowload'
  put '/sections/:id/update', to: 'section_processes#update_section', as: 'section_update'
  put '/sections/:id/attendances/:attendance_id/update', to: 'section_processes#update_section_attendance', as: 'section_attendance_update'
  put '/sections/:id/seatworks/:seatwork_id/update', to: 'section_processes#update_section_seatwork', as: 'section_seatwork_update'
  put '/sections/:id/homeworks/:homework_id/update', to: 'section_processes#update_section_homework', as: 'section_homework_update'
  put '/sections/:id/projects/:project_id/update', to: 'section_processes#update_section_project', as: 'section_project_update'
  put '/sections/:id/exams/:exam_id/update', to: 'section_processes#update_section_exam', as: 'section_exam_update'
  delete '/sections/:id/delete', to: 'section_processes#destroy_section', as: 'section_delete'
  delete '/sections/:id/seatworks/:seatwork_id/delete', to: 'section_processes#destroy_section_seatwork', as: 'section_seatwork_delete'
  delete '/sections/:id/homeworks/:homework_id/delete', to: 'section_processes#destroy_section_homework', as: 'section_homework_delete'
  delete '/sections/:id/projects/:project_id/delete', to: 'section_processes#destroy_section_project', as: 'section_project_delete'
  delete '/sections/:id/exams/:exam_id/delete', to: 'section_processes#destroy_section_exam', as: 'section_exam_delete'
  delete '/sections/:id/attendances/:attendance_id/delete', to: 'section_processes#destroy_section_attendance', as: 'section_attendance_delete'

  # STUDENT SUBMODELS
  get '/sections/:id/students', to: 'students#index', as: 'students'
  get '/sections/:id/students/:student_id', to: 'students#show', as: 'student'
  get '/sections/:id/students/:student_id/homeworks', to: 'students#view_homeworks', as: 'view_student_homeworks'
  get '/sections/:id/students/:student_id/seatworks', to: 'students#view_seatworks', as: 'view_student_seatworks'
  get '/sections/:id/students/:student_id/projects', to: 'students#view_projects', as: 'view_student_projects'
  get '/sections/:id/students/:student_id/exams', to: 'students#view_exams', as: 'view_student_exams'
  get '/sections/:id/students/:student_id/absences', to: 'students#view_absences', as: 'view_student_absences'

  # STUDENT PROCESSES
  post '/sections/:id/students/:student_id/report', to: 'student_processes#student_report_to_email', as: 'student_report'
  get '/sections/:id/students/:student_id/report', to: 'student_processes#download_report', as: 'student_report_dowload'
  put '/sections/:id/students/:student_id/update', to: 'student_processes#update_student', as: 'student_update'
  put '/sections/:id/students/:student_id/seatworks/:seatwork_id', to: 'student_processes#update_student_seatwork', as: 'student_update_seatwork'
  put '/sections/:id/students/:student_id/homeworks/:homework_id', to: 'student_processes#update_student_homework', as: 'student_update_homework'
  put '/sections/:id/students/:student_id/projects/:project_id', to: 'student_processes#update_student_project', as: 'student_update_project'
  put '/sections/:id/students/:student_id/exams/:exam_id', to: 'student_processes#update_student_exam', as: 'student_update_exam'
  delete '/sections/:id/students/:student_id/delete', to: 'student_processes#destroy_student', as: 'student_delete'
  delete '/sections/:id/students/:student_id/seatworks/:seatwork_id/delete', to: 'student_processes#destroy_student_seatwork', as: 'student_delete_seatwork'
  delete '/sections/:id/students/:student_id/homeworks/:homework_id/delete', to: 'student_processes#destroy_student_homework', as: 'student_delete_homework'
  delete '/sections/:id/students/:student_id/projects/:project_id/delete', to: 'student_processes#destroy_student_project', as: 'student_delete_project'
  delete '/sections/:id/students/:student_id/exams/:exam_id/delete', to: 'student_processes#destroy_student_exam', as: 'student_delete_exam'
  delete '/sections/:id/students/:student_id/absences/:absent_id/delete', to: 'student_processes#destroy_student_attendance', as: 'student_delete_attendance'
  
  # FORMS
  get '/new/section', to: 'form#new_section', as: 'new_section_form'
  get '/new/grading-system', to: 'form#new_grading_system', as: 'new_grading_system_form'
  get '/new/seatwork/:section_id', to: 'form#new_seatwork', as: 'new_seatwork_form'
  get '/new/homework/:section_id', to: 'form#new_homework', as: 'new_homework_form'
  get '/new/project/:section_id', to: 'form#new_project', as: 'new_project_form'
  get '/new/exam/:section_id', to: 'form#new_exam', as: 'new_exam_form'
  get '/new/attendance/:section_id', to: 'form#new_attendance', as: 'new_attendance_form'

  # PROCESS FORMS
  post '/new/section', to: 'creation_processes#create_section', as: 'create_section'
  post '/new/grading-system', to: 'creation_processes#create_grading_system', as: 'create_grading_system'
  post '/new/seatwork/:section_id', to: 'creation_processes#create_seatwork', as: 'create_seatwork'
  post '/new/homework/:section_id', to: 'creation_processes#create_homework', as: 'create_homework'
  post '/new/project/:section_id', to: 'creation_processes#create_project', as: 'create_project'
  post '/new/exam/:section_id', to: 'creation_processes#create_exam', as: 'create_exam'
  post '/new/attendance/:section_id/', to: 'creation_processes#create_attendance', as: 'create_attendance'
end

app/models/section.rb
class Section < ApplicationRecord
  validates :name, presence: true
  validates :active_quarter, inclusion: 1..4
  belongs_to :teacher
  belongs_to :grading_system
  has_many :students, dependent: :destroy
  has_many :quarters, dependent: :destroy
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_section, except: [:index]
  before_action :set_active_quarter, except: %i[index show]

  def index
    @sections = Section.where(teacher: current_teacher)
  end

  def show; end

  def view_seatworks
    @seatworks = @active_quarter.seatworks
  end

  def view_homeworks
    @homeworks = @active_quarter.homeworks
  end

  def view_projects
    @projects = @active_quarter.projects
  end

  def view_exams
    @exams = @active_quarter.exams
  end

  def view_attendances
    @absences = {}
    @attendances = @active_quarter.attendances
    @attendances.each { |attendance| @absences[attendance.id] = attendance.student_absents.length }
  end

  private

  def set_section
    @section = Section.find_by(id: params[:id], teacher: current_teacher)
  end

  def set_active_quarter
    @active_quarter = @section.quarters.find_by(sequence: @section.active_quarter)
  end
end

app/views/sections/index.html.erb
<h1>Hi Maam/Sir, this is where you view the list of all sections that you are teaching</h1>

app/views/sections/show.html.erb
<!-- <h1>Hi Maam/Sir, this is where you view the details of a section</h1> -->

<div class="card shadow mb-4 mesa">
  <div class="card-header py-3 table-responsive d-flex justify-content-around">
    <h5 class="m-0 text-muted mb-2">QUARTER : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.active_quarter %></h5>
    <h5 class="m-0 text-muted mb-2">SECTION : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.name.upcase %></h5>
    <h5 class="m-0 text-muted mb-2">NO. OF STUDENTS : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.students.count %></span></h5>
  </div>
  <div class="card-body">
    <div class="d-sm-flex justify-content-between mb-5">
      <div>
        <a class="btn btn-warning btn-circle text-center mr-2" href="#" data-toggle="modal" data-target="#updateSectionModal_<%= @section.id %>">
          <i class="fas fa-pencil-alt"></i>
        </a>
        <a class="btn btn-danger btn-circle text-center" href="#" data-toggle="modal" data-target="#deleteSectionModal_<%= @section.id %>">
          <i class="fas fa-trash"></i>
        </a>
      </div>
      <div>
        <%= link_to section_report_path(@section), method: 'post', class: 'btn btn-primary btn-icon-split ml-auto' do %>
          <span class="icon text-white-50">
            <i class="fas fa-paper-plane"></i>
          </span>
          <span class="text">Send Report to Email</span>
        <% end %>

        <%= link_to section_report_dowload_path(@section), class: 'btn btn-primary btn-icon-split ml-auto' do %>
          <span class="icon text-white-50">
            <i class="fas fa-download"></i>
          </span>
          <span class="text">Download Report</span>
        <% end %>
      </div>
    </div>
    <div class="row d-flex justify-content-around">
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_section_seatworks_path(@section.id) %>">
          <div class="card border rounded shadow h-100 py-2" style="background: #AB4967">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-book-reader fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-4">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2 text-light">SEATWORK</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_section_homeworks_path(@section.id) %>">
          <div class="card border rounded shadow h-100 py-2" style="background: #5B8266">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-home fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-3">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2 text-light">HOMEWORK</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <div class="row d-flex justify-content-around">
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_section_projects_path(@section.id) %>">
          <div class="card border rounded shadow h-100 py-2" style="background: #785589">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-project-diagram fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-4">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2 text-light">PROJECTS</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_section_exams_path(@section.id) %>">
          <div class="card border rounded shadow h-100 py-2" style="background: #B49A67">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-file-signature fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-3">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2 text-light">EXAMS</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-xl-6 col-md-6 mb-4">
        <a href="<%= view_section_attendances_path(@section.id) %>">
          <div class="card border rounded shadow h-100 py-2" style="background: #A2708A">
            <div class="card-body m-auto">
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <i class="fas fa-user-check fa-2x text-gray-300"></i>
                </div>
                <div class="col ml-3">
                  <div class="text-bg font-weight-bold text-uppercase mb-1 h2 text-light">ATTENDANCE</div>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<%# UPDATE SECTION MODAL %>
  <div class="modal fade" id="updateSectionModal_<%= @section.id %>" tabindex="-1" role="dialog" aria-labelledby="section_update_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Section</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="mb-4 font-weight-bold h6 text-dark text-center">You are about to make changes to a section's details.</p>
          <%= form_with method: :put, scope: :section, url: section_update_path(id: @section.id), local: true do |f| %>
            <div class="text-center">
              <div class="form-group">
                <%= f.label :'section name', class: "text-uppercase small" %>
                <%= f.text_field :name, required: true, class: "form-control m-auto text-center", 'style': "width: 50%" %>
              </div>
              <div class="form-group">
                <%= f.label :active_quarter, class: "text-uppercase small" %>
                <%= f.number_field :active_quarter, required: true, class: "form-control m-auto text-center", 'style': "width: 50%", 'min': '1', 'max': '4' %>
              </div>
            </div>
            <div class="text-center">
            <%= f.submit "UPDATE", class:'btn btn-warning text-center', 'style': "width: 50%" %></br>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

<%# DELETE SECTION MODAL %>
  <div class="modal fade" id="deleteSectionModal_<%= @section.id %>" tabindex="-1" role="dialog" aria-labelledby="section_delete_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Section</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <p class="mb-2 font-weight-bold h3 text-dark"><%= @section.name.upcase %></p>
          <p class="text-danger h6">Are you sure you want to delete this record?<br>This process cannot be undone.</p><br>
          <%= link_to 'DELETE', section_delete_path(id: @section.id), class: 'btn btn-danger px-5', method: :delete %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>

app/views/sections/view_attendances.html.erb
<!-- <h1>Hi Maam/Sir, this is where you view the attendance of a section depending on current active_quarter</h1> -->

<div class="card shadow mb-4 mesa">
  <div class="card-header py-3 table-responsive d-flex justify-content-around">
    <h5 class="m-0 text-muted mb-2">QUARTER : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.active_quarter %></h5>
    <h5 class="m-0 text-muted mb-2">SECTION : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.name.upcase %></h5>
    <h5 class="m-0 text-muted mb-2">NO. OF STUDENTS : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.students.count %></span></h5>
  </div>
  <div class="m-auto">
    <a href="<%= new_attendance_form_path(@section.id) %>" class="btn btn-success btn-icon-split mt-3">
      <span class="icon text-white-50">
        <i class="fas fa-plus"></i>
      </span>
      <span class="text">New Attendance</span>
    </a>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="200" cellspacing="0">
        <thead style="background: #A2708A; color: white">
          <tr>
            <th scope="col">DATE OF ATTENDANCE</th>
            <th scope="col">ABSENT</th>
            <th scope="col">PRESENT</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @attendances.each do |attendance| %>
            <tr>
              <td><%= attendance.date.strftime("%d - %^B - %Y, %^A") %></td>
              <td><%= @absences[attendance.id] %></td>
              <td><%= @section.students.count - @absences[attendance.id] %></td>
              <td>
                <div class="d-flex justify-content-around">
                  <a class="btn btn-warning btn-circle text-center" href="#" data-toggle="modal" data-target="#updateAttendanceModal_<%= attendance.id %>">
                      <i class="fas fa-pencil-alt"></i>
                  </a>
                  <a class="btn btn-danger btn-circle text-center" href="#" data-toggle="modal" data-target="#deleteAttendanceModal_<%= attendance.id %>">
                      <i class="fas fa-trash"></i>
                  </a>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
        <!-- <tfoot>
          <tr class="text-dark">
            <th scope="col" style="color: #A2708A">COUNT</th>
            <th class="font-weight-bold text-center" style="color: #A2708A"><%= @attendances.count %></th>
          </tr>
        </tfoot> -->
      </table>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', section_path(@section.id), class: "btn btn-info px-4 font-weight-bold", 'style': "background: #A2708A; border-color: #A2708A;" %>
</div>

<%# UPDATE ATTENDANCE MODAL %>
<% @attendances.each do |attendance| %>
  <div class="modal fade" id="updateAttendanceModal_<%= attendance.id %>" tabindex="-1" role="dialog" aria-labelledby="attendance_update_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Attendance</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="mb-4 font-weight-bold h3 text-dark text-center"><%= attendance.date.strftime("%d-%^B-%Y, %^A") %></p>
          <%= form_with method: :put, scope: :quarter, url: section_attendance_update_path(id: @section.id, attendance_id: attendance.id), local: true do |f| %>
            <div class="text-center">
              <div class="form-group">
                <%= f.date_field :date, required: true, class: "form-control m-auto text-center", 'style': "width: 50%" %>
              </div>
            </div>
            <div class="text-center">
              <%= f.submit "UPDATE", class:'btn btn-warning text-center', 'style': "width: 50%" %></br>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

<%# DELETE ATTENDANCE MODAL %>
<% @attendances.each do |attendance| %>
  <div class="modal fade" id="deleteAttendanceModal_<%= attendance.id %>" tabindex="-1" role="dialog" aria-labelledby="attendance_delete_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Attendance</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <p class="mb-2 font-weight-bold h3 text-dark"><%= attendance.date.strftime("%d-%^B-%Y, %^A") %></p>
          <p class="text-danger h6">Are you sure you want to delete this record?<br>This process cannot be undone.</p><br>
          <%= link_to 'DELETE', section_attendance_delete_path(id: @section.id, attendance_id: attendance.id), class: 'btn btn-danger px-5', method: :delete %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sections/view_exams.html.erb
<!-- <h1>Hi Maam/Sir, this is where you view the exams of a section depending on current active_quarter</h1> -->

<div class="card shadow mb-4 mesa">
  <div class="card-header py-3 table-responsive d-flex justify-content-around">
    <h5 class="m-0 text-muted mb-2">QUARTER : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.active_quarter %></h5>
    <h5 class="m-0 text-muted mb-2">SECTION : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.name.upcase %></h5>
    <h5 class="m-0 text-muted mb-2">NO. OF STUDENTS : <span class="ml-3 px-3 text-light font-weight-bold bg-primary rounded"><%= @section.students.count %></span></h5>
  </div>
  <div class="m-auto">
    <a href="<%= new_exam_form_path(@section.id) %>" class="btn btn-success btn-icon-split mt-3">
      <span class="icon text-white-50">
        <i class="fas fa-plus"></i>
      </span>
      <span class="text">New Exam</span>
    </a>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="200" cellspacing="0">
        <thead style="background: #B49A67; color: white">
          <tr>
            <th scope="col">EXAM</th>
            <th scope="col">Max Score</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @exams.each do |exam| %>
            <tr>
              <td><%= exam.title %></td>
              <td style="color: #B49A67" class="font-weight-bold"><%= exam.max_score %></td>
              <td>
                <div class="d-flex justify-content-around">
                  <a class="btn btn-warning btn-circle text-center" href="#" data-toggle="modal" data-target="#updateExamModal_<%= exam.id %>">
                      <i class="fas fa-pencil-alt"></i>
                  </a>
                  <a class="btn btn-danger btn-circle text-center" href="#" data-toggle="modal" data-target="#deleteExamModal_<%= exam.id %>">
                      <i class="fas fa-trash"></i>
                  </a>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>    
      </table>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'GO BACK', section_path(@section.id), class: "btn btn-info px-4 font-weight-bold", 'style': "background: #B49A67; border-color: #B49A67;" %>
</div>

<%# UPDATE EXAM MODAL %>
<% @exams.each do |exam| %>
  <div class="modal fade" id="updateExamModal_<%= exam.id %>" tabindex="-1" role="dialog" aria-labelledby="exam_update_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Exam</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="mb-4 font-weight-bold h3 text-dark text-center"><%= exam.title.upcase %></p>
          <%= form_with method: :put, scope: :quarter, url: section_exam_update_path(id: @section.id, exam_id: exam.id), local: true do |f| %>
            <div class="text-center">
              <div class="form-group">
                <%= f.text_field :title, 'placeholder': 'Title', required: true, class: "form-control m-auto text-center", 'style': "width: 50%" %>
              </div>
              <div class="form-group">
                <%= f.number_field :max_score, 'placeholder': 'Max Score', required: true, class: "form-control m-auto text-center", 'style': "width: 50%" %>
              </div>
            </div>
            <div class="text-center">
            <%= f.submit "UPDATE", class:'btn btn-warning text-center', 'style': "width: 50%" %></br>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

<%# DELETE EXAM MODAL %>
<% @exams.each do |exam| %>
  <div class="modal fade" id="deleteExamModal_<%= exam.id %>" tabindex="-1" role="dialog" aria-labelledby="exam_delete_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Exam</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <p class="mb-2 font-weight-bold h3 text-dark"><%= exam.title.upcase %></p>
          <p class="text-danger h6">Are you sure you want to delete this record?<br>This process cannot be undone.</p><br>
          <%= link_to 'DELETE', section_exam_delete_path(id: @section.id, exam_id: exam.id), class: 'btn btn-danger px-5', method: :delete %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>